name: willgo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.5.3
dependencies:
  another_stepper: ^1.2.2
  badges: ^3.1.2
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dots_indicator: ^3.0.0
  file_picker: ^8.0.7
  firebase_core: ^3.1.0
  firebase_messaging: ^15.1.1
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.2
  flutter_html: any
  flutter_iconly: ^1.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_marker_popup: ^5.2.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.0
  flutter_social_button: ^1.1.4+1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.7.0
  form_builder_extra_fields: ^11.0.0
  freezed_annotation: ^2.4.1
  geocoding: ^2.2.1+1
  geolocator: ^13.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_maps_webapi: ^0.0.22
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  latlong2: ^0.9.0
  logger: ^2.4.0
  myfatoorah_flutter: ^3.1.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  responsive_framework: ^1.4.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  timeago: ^3.3.0
  timer_count_down: ^2.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.10

  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconLuncher.jpeg"
  remove_alpha_ios: true

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translation/
    - assets/countries/
