// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJBJNGdn2bnTnnjgv_tDDmIA7ByCqUGXw',
    appId: '1:208283883833:web:5d10684d456b0857df70e8',
    messagingSenderId: '208283883833',
    projectId: 'willgo-259ee',
    authDomain: 'willgo-259ee.firebaseapp.com',
    storageBucket: 'willgo-259ee.appspot.com',
    measurementId: 'G-RDK0129J1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkehmZRQvxUP_Gz8pGaEDUxue6B8zvQsk',
    appId: '1:208283883833:android:0d4de0ff8f65081edf70e8',
    messagingSenderId: '208283883833',
    projectId: 'willgo-259ee',
    storageBucket: 'willgo-259ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlIg44vsnBBnTk7XbAF71lwJ8K4ZQ50kw',
    appId: '1:208283883833:ios:bb135e45e5449543df70e8',
    messagingSenderId: '208283883833',
    projectId: 'willgo-259ee',
    storageBucket: 'willgo-259ee.appspot.com',
    iosBundleId: 'com.rowad.willgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlIg44vsnBBnTk7XbAF71lwJ8K4ZQ50kw',
    appId: '1:208283883833:ios:eed9cd83bd3f43b5df70e8',
    messagingSenderId: '208283883833',
    projectId: 'willgo-259ee',
    storageBucket: 'willgo-259ee.appspot.com',
    iosBundleId: 'com.rowad.willgo.willgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJBJNGdn2bnTnnjgv_tDDmIA7ByCqUGXw',
    appId: '1:208283883833:web:acc0c2d7ae3d9d16df70e8',
    messagingSenderId: '208283883833',
    projectId: 'willgo-259ee',
    authDomain: 'willgo-259ee.firebaseapp.com',
    storageBucket: 'willgo-259ee.appspot.com',
    measurementId: 'G-QE4BHHWSS1',
  );
}
