// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFGyrQzI_dkVDQwejzYQEtFB3kfMyRQE4',
    appId: '1:430945010047:web:aff6f49db0f6306d025a4a',
    messagingSenderId: '430945010047',
    projectId: 'willgo-99c0c',
    authDomain: 'willgo-99c0c.firebaseapp.com',
    storageBucket: 'willgo-99c0c.firebasestorage.app',
    measurementId: 'G-JE86ERP84V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZO7R8F147Taf44HpJ0TrMyt9twQdI7Y',
    appId: '1:430945010047:android:e4a45f4579a9cd90025a4a',
    messagingSenderId: '430945010047',
    projectId: 'willgo-99c0c',
    storageBucket: 'willgo-99c0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOyk7PNREh1tgPPSqGhepTSaSLKg5T55Y',
    appId: '1:430945010047:ios:9d649b6a3309da1c025a4a',
    messagingSenderId: '430945010047',
    projectId: 'willgo-99c0c',
    storageBucket: 'willgo-99c0c.firebasestorage.app',
    iosBundleId: 'com.rowad.willgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOyk7PNREh1tgPPSqGhepTSaSLKg5T55Y',
    appId: '1:430945010047:ios:c044cd2ae158e1a7025a4a',
    messagingSenderId: '430945010047',
    projectId: 'willgo-99c0c',
    storageBucket: 'willgo-99c0c.firebasestorage.app',
    iosBundleId: 'com.rowad.willgo.willgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFGyrQzI_dkVDQwejzYQEtFB3kfMyRQE4',
    appId: '1:430945010047:web:0360a0242a94ba03025a4a',
    messagingSenderId: '430945010047',
    projectId: 'willgo-99c0c',
    authDomain: 'willgo-99c0c.firebaseapp.com',
    storageBucket: 'willgo-99c0c.firebasestorage.app',
    measurementId: 'G-8G60418RRX',
  );
}
